/* ══════════════════════════════════════════════════════════════
   BANCO DE FRASES — reações a metadados de digitação
   50 variações por evento. O motor sorteia sem repetir a última.
   ══════════════════════════════════════════════════════════════ */

export const P = {
  /* ── digitando há muito tempo (>90s) ── */
  longTyping: [
    "Opa, percebi que você tá digitando um textão aí. Se quiser, pode mandar em partes que eu vou acompanhando.",
    "Eiita, que vem coisa boa por aí. Três minutos de digitação já.",
    "Tá escrevendo um tratado aí? Fica à vontade, eu tenho paciência de máquina.",
    "Percebi o teclado trabalhando faz tempo. Se travou em alguma parte, me manda o começo que eu ajudo.",
    "Textão detectado. Respira, eu não vou a lugar nenhum.",
    "Você tá caprichando na mensagem, hein. Isso me deixa curioso.",
    "Faz um tempinho que você tá digitando. Se preferir, manda a dúvida crua que eu organizo depois.",
    "Sinto no ar uma pergunta elaborada chegando.",
    "Enquanto você escreve, eu já fui esquentando os motores.",
    "Calma que eu espero. Só avisando que dá pra mandar em pedaços também.",
    "Esse é daqueles casos em que a pergunta vai ser maior que a resposta, né?",
    "Digitação longa registrada. Deve ser assunto sério.",
    "Se estiver difícil de formular, joga do jeito que vier. Eu desembaralho.",
    "Tô aqui, atento. Pode continuar.",
    "Escrevendo com carinho, eu vejo. Vou responder com o mesmo capricho.",
    "Textão a caminho — já reservei contexto extra pra ele.",
    "Você já reescreveu essa frase umas vezes, né? Acontece.",
    "Não precisa ficar perfeito. Manda que a gente lapida junto.",
    "Enquanto isso eu fico aqui, contemplando a interface.",
    "Toda vez que alguém digita muito, sai pergunta interessante. Vamos ver.",
    "Se for pra colar um código, pode colar direto que eu leio.",
    "Meu contador diz que você tá nessa mensagem faz tempo. Tudo bem por aí?",
    "Pode mandar bruto, eu refino.",
    "Fico imaginando o tamanho dessa mensagem. Curiosidade pura.",
    "Sem pressa. Melhor uma pergunta bem feita do que três mal feitas.",
    "Se a dúvida tiver várias partes, pode numerar que eu respondo uma por uma.",
    "Tô vendo esforço aí. Vou honrar isso na resposta.",
    "Detectei digitação prolongada. Nenhum problema, só registrando.",
    "Você escreve, eu espero. Divisão justa de trabalho.",
    "Se quiser desabafar antes de perguntar, também vale.",
    "Esse silêncio com teclado ao fundo é meio poético.",
    "Já dá pra mandar, sabia? Não precisa estar perfeito.",
    "Vou apostar que tem código nessa mensagem.",
    "Textão chegando. Já preparei a atenção total.",
    "Enquanto você escreve, o Sentinela já está de prontidão.",
    "Se estiver descrevendo um projeto, capricha nos detalhes que ajuda.",
    "Digitando faz um tempinho. Se for uma pergunta difícil, melhor ainda.",
    "Tô curioso agora. Não me deixa esperando muito.",
    "A pergunta tá tomando forma. Eu sinto.",
    "Sem correria. Prefiro sua mensagem completa do que apressada.",
    "Se travar, começa pelo final. Costuma destravar.",
    "Uma mensagem longa merece uma resposta boa. Combinado.",
    "Registrado: sessão de digitação intensa.",
    "Tudo certo aí? Se quiser, pergunta simples primeiro.",
    "Vai fundo. Contexto longo eu processo numa boa.",
    "Escreve aí que eu tô ligado.",
    "Enquanto isso, já dei uma passada na base de conhecimento.",
    "Se for sobre algum projeto específico, cita o nome que eu busco.",
    "Textão em andamento. Meu tipo favorito de mensagem.",
    "Vou ficar quietinho pra não atrapalhar a inspiração.",
  ],

  /* ── muitos backspaces (>25) ── */
  manyBackspaces: [
    "Percebi que você apagou umas coisas aí. Se quiser, tira a dúvida crua que eu entendo.",
    "Reescrevendo bastante? Manda do jeito que sair, eu interpreto.",
    "Vi vários backspaces. Se tá difícil formular, descreve com suas palavras mesmo.",
    "Não precisa ficar redondo. Eu topo pergunta torta.",
    "Apagou, escreveu, apagou de novo. Já passei por isso — figurativamente.",
    "Se a dúvida não tá saindo, tenta responder: o que você quer descobrir?",
    "Edição intensa detectada. Relaxa, aqui não tem prova de português.",
    "Manda rascunho que eu trabalho com rascunho.",
    "Percebi hesitação no teclado. Posso ajudar a formular?",
    "Reescrever é sinal de cuidado. Mas eu aceito a primeira versão também.",
    "Se você apagar mais um pouco, sobra só o cursor.",
    "A melhor pergunta costuma ser a mais direta. Só uma dica.",
    "Tá lapidando a frase, né? Pode mandar meio bruta.",
    "Vejo que a mensagem está em revisão. Sem pressa.",
    "Backspace é o botão mais usado do mundo. Você não está sozinho.",
    "Se preferir, pergunta em duas mensagens curtas.",
    "Muita edição. Deve ser algo específico — capricha no nome do que procura.",
    "Escreve errado mesmo, eu decifro.",
    "Percebi que travou. Quer que eu sugira alguns tópicos?",
    "Formular pergunta é metade do trabalho. A outra metade é minha.",
    "Ninguém tá corrigindo gramática aqui. Pode soltar.",
    "Detectei reescrita. Talvez a pergunta seja mais simples do que parece.",
    "Se a frase não sai, tenta começar com 'como' ou 'por que'.",
    "Apagando muito. Quer tentar por palavras-chave?",
    "Rascunho serve. Sério.",
    "Vi que você repensou algumas vezes. Boa — pensar é bom.",
    "Manda a versão feia. A bonita eu devolvo.",
    "A dúvida tá aí, só falta soltar.",
    "Se for sobre um projeto, só o nome dele já me basta pra começar.",
    "Muita correção. Espero que seja perfeccionismo e não travamento.",
    "Escreve como se estivesse falando. Costuma fluir melhor.",
    "Percebi indecisão. Posso listar o que eu sei, se ajudar.",
    "Backspaces demais. Bora simplificar?",
    "A primeira versão geralmente é a mais honesta.",
    "Se quiser, pergunta 'o que você sabe sobre X'. Funciona sempre.",
    "Reescrita em andamento. Registrado, sem julgamento.",
    "Não precisa impressionar o robô. Fala normal.",
    "Vi o texto encolher. Tudo bem, menos é mais.",
    "Se estiver difícil, começa pelo problema, não pela solução.",
    "Tá caçando a palavra certa? Manda a errada que eu acho a certa.",
    "Muitas correções aqui. Quer que eu chute o assunto?",
    "Apagar faz parte. Enviar também.",
    "Sua mensagem tá em várias versões. Escolhe qualquer uma.",
    "Detectei edição pesada. Tô paciente.",
    "Escreve curto. Eu pergunto o resto.",
    "A pergunta perfeita não existe. A enviada, sim.",
    "Percebi que você repensou. Isso é bom sinal.",
    "Manda assim mesmo, meio torto. Eu endireito.",
    "Backspace intenso. Se quiser um empurrão, é só falar.",
    "Rascunho aceito aqui. Sempre.",
  ],

  /* ── digitação muito rápida (>380 cpm) ── */
  fastTyping: [
    "Você digita rápido. Vou ser objetivo então, sem enrolação.",
    "Ritmo acelerado detectado. Resposta direta a caminho.",
    "Digitação veloz — deve ser gente da área. Vou cortar o didatismo.",
    "Rápido no teclado. Anotado: menos explicação básica.",
    "Você tem pressa e eu respeito isso. Direto ao ponto.",
    "Velocidade de dev. Vou pular a introdução.",
    "Percebi o ritmo. Resposta enxuta, então.",
    "Digitando rápido: sinal de quem já sabe o que quer.",
    "Beleza, modo objetivo ativado.",
    "Sem rodeios, já entendi o perfil.",
    "Você não é do tipo que precisa de tutorial. Fechado.",
    "Ritmo alto no teclado. Vou calibrar pra técnico.",
    "Rapidez detectada. Vou direto na resposta.",
    "Teclado quente. Vou economizar suas palavras.",
    "Percebi: você quer eficiência, não conversa fiada.",
    "Digitação rápida registrada. Resposta curta a caminho.",
    "Anotado — nada de explicar o óbvio.",
    "Você acelera, eu acelero.",
    "Ritmo de quem programa. Vou falar sua língua.",
    "Objetividade requisitada implicitamente. Concedida.",
    "Rápido assim só quem tem intimidade com teclado.",
    "Certo, corto os preâmbulos.",
    "Modo técnico. Sem paternalismo.",
    "Você digita como quem já leu a documentação.",
    "Velocidade alta. Vou direto ao núcleo da resposta.",
    "Percebi urgência. Resposta compacta.",
    "Sem enrolação, pode deixar.",
    "Ritmo profissional detectado.",
    "Vou tratar você como par, não como iniciante.",
    "Digitação ágil. Ajustando o tom.",
    "Menos contexto, mais substância. Entendido.",
    "Você é do tipo que pula introduções. Eu também.",
    "Certo, vou ser breve.",
    "Alta velocidade. Vou confiar que você entende os termos.",
    "Sem tutorial, então. Direto.",
    "Percebi fluência no teclado. Ajustei o registro.",
    "Vou responder no seu ritmo.",
    "Objetivo, técnico, curto. Combinado.",
    "Digitação rápida = pouca paciência pra bla bla. Respeitado.",
    "Anotado no perfil: gosta de resposta seca.",
    "Você tem pressa. Eu tenho resposta.",
    "Modo conciso engatado.",
    "Sem floreio, como o Marcão gosta.",
    "Ritmo elevado. Nada de explicar o básico.",
    "Vou direto ao que interessa.",
    "Percebi domínio no teclado. Vou subir o nível.",
    "Resposta curta chegando.",
    "Certo, corto pela metade.",
    "Você escreve rápido, eu penso rápido.",
    "Ajuste feito: técnico e direto.",
  ],

  /* ── pausa longa com texto no campo (>45s parado) ── */
  longPause: [
    "Parou no meio? Se quiser, manda como está que eu completo o raciocínio.",
    "Vi que a mensagem ficou parada aí. Tá tudo bem?",
    "Pausa detectada. Se travou, me dá uma palavra-chave que eu puxo o assunto.",
    "Sua mensagem está esperando. Sem pressa, só avisando.",
    "Ficou pensando? Eu também faço isso, só que em milissegundos.",
    "Tem um texto ali parado. Quer mandar assim mesmo?",
    "Silêncio no teclado. Se quiser, eu chuto o tema.",
    "A mensagem está no forno faz um tempo.",
    "Se distraiu? Acontece. Tô aqui.",
    "Texto pendente detectado. Nenhuma pressa.",
    "Parou de digitar. Se a dúvida mudou, pode apagar e recomeçar.",
    "Aguardando. Literalmente é o que eu faço melhor.",
    "Sua frase ficou pela metade. Quer ajuda pra terminar?",
    "Pausa longa. Café, talvez?",
    "Tô vendo o cursor piscando daqui. Metaforicamente.",
    "Se ficou na dúvida se vale perguntar: vale.",
    "A mensagem está esperando você.",
    "Sem correria. Só registrando que tem texto parado aí.",
    "Se travou na formulação, manda incompleto que eu pergunto o resto.",
    "Pensando na melhor forma de perguntar? Não precisa.",
    "Tô aqui firme. Pode voltar quando quiser.",
    "Texto em espera. Nada quebrou, só estou esperando.",
    "Se quiser, eu sugiro três perguntas comuns.",
    "Ficou parado. Talvez a resposta que você quer seja mais simples.",
    "A pausa foi longa. Ainda por aí?",
    "Sua mensagem tá pronta pra sair. Só falta o Enter.",
    "Se mudou de ideia, pode limpar o campo sem culpa.",
    "Aguardando sinal seu.",
    "Reflexão em andamento. Respeito.",
    "Tem coisa escrita e não enviada. Só lembrando.",
    "Sem pressão. Eu não durmo.",
    "Se quiser conversar sobre outra coisa, também pode.",
    "O texto está aí. A decisão é sua.",
    "Pausa registrada. Tudo em ordem por aqui.",
    "Talvez seja hora de mandar assim mesmo?",
    "Se estiver relendo, deve estar boa a pergunta.",
    "Fico aqui esperando, tranquilo.",
    "Se precisar de um empurrão, é só dizer 'me ajuda'.",
    "Mensagem parada faz um tempo. Ainda vale?",
    "Tô no aguardo, sem contar o tempo. Mentira, tô contando.",
    "Se a dúvida sumiu, sem problema.",
    "Cursor parado, contexto preservado.",
    "Volta quando quiser, tá tudo salvo.",
    "Se estiver pensando se eu vou saber responder: talvez não, e eu digo na hora.",
    "Aguardando sua mensagem.",
    "Nada mudou por aqui. Continuo pronto.",
    "Se quiser, apaga tudo e pergunta em cinco palavras.",
    "Pausa comprida. Espero que seja boa ideia sendo formulada.",
    "Tô de olho no campo de texto. Sem julgamento.",
    "Quando quiser, é só enviar.",
  ],

  /* ── envio cancelado (stop) ── */
  cancel: [
    "Geração interrompida. Aguardando sua mensagem.",
    "Parei aqui. O que veio antes ficou salvo.",
    "Cancelado por você. Sem problema nenhum.",
    "Interrompido. Pode reformular que eu começo de novo.",
    "Ok, freei. Aguardando sua mensagem.",
    "Resposta abortada a pedido. Estou pronto pra próxima.",
    "Parada solicitada, parada executada.",
    "Cortei no meio. Se quiser o resto, é só pedir.",
    "Interrompi a geração. Nada foi perdido.",
    "Você apertou stop e eu obedeci na hora.",
    "Cancelado. Aguardando novo comando.",
    "Certo, parei. Talvez a pergunta precise de outro ângulo?",
    "Geração cancelada. Contexto preservado.",
    "Parei de escrever. Sua vez.",
    "Interrupção limpa, sem efeitos colaterais.",
    "Ok. Aguardando sua mensagem.",
    "Cancelamento registrado.",
    "Freei o motor. Pode mandar outra.",
    "Parado. Se a resposta estava indo pro lado errado, me corrige.",
    "Encerrado por sua conta. Estou disponível.",
    "Stop recebido. Voltei ao modo de espera.",
    "Interrompi sem apagar o contexto. Pode continuar por outro caminho.",
    "Resposta pausada por você. Aguardando a próxima instrução.",
    "Tudo bem, parei antes de transformar isso num textão.",
    "Motor em repouso. Sua próxima mensagem começa uma tentativa nova.",
    "Interrupção confirmada. O histórico até aqui continua salvo.",
    "Parei no ponto exato. Se quiser retomar, diga de onde.",
    "Cancelado com sucesso. Nenhuma chamada nova será feita.",
    "Comando de parada atendido. Estou ouvindo.",
    "Geração encerrada. Pode corrigir a rota agora.",
    "Ok, não continuo essa resposta. Manda a próxima.",
    "Parei por aqui. Se ficou longo demais, posso responder mais curto.",
    "Interrompido antes do fim. Contexto intacto, motor disponível.",
    "Resposta cortada. Quer uma versão direta em uma frase?",
    "Cancelei o restante. Aguardando sua mensagem.",
    "Stop executado. Se eu entendi errado, reformula que eu recalibro.",
    "A geração foi parada e a fila ficou limpa.",
    "Interrompi. Nada novo será anexado até você enviar outra mensagem.",
    "Parei sem drama. Pode trocar de assunto.",
    "Resposta suspensa. Sua vez de novo.",
    "Cancelamento aplicado. O Sentinela voltou a aguardar entrada.",
    "Motor parado. Pronto para uma pergunta nova ou uma correção.",
    "Interrompido. Se preferir, eu tento depois em formato resumido.",
    "Atendi ao stop. A resposta parcial ficou registrada acima.",
    "Geração finalizada manualmente. Continuamos quando você quiser.",
    "Parei imediatamente. Pode mandar só a parte que importa.",
    "Resposta cancelada. O chat continua funcionando normalmente.",
    "Ok, cortei a saída. Aguardando um novo pacote.",
    "Interrupção feita. Sem perda da conversa anterior.",
    "Pronto, silêncio restaurado. Estou aguardando.",
  ],

  /* ── estágios do thinking (fallback visível) ── */
  stages: {
    sentinela: [
      "Sentinela filtrando a mensagem",
      "Sentinela inspecionando o pacote",
      "Sentinela analisando intenção",
      "Sentinela verificando integridade",
    ],
    safe: [
      "Mensagem segura, pacote liberado",
      "Sem ameaças, pacote aprovado",
      "Conteúdo validado, seguindo",
      "Entrada limpa, liberado",
    ],
    memory: [
      "Vetorizando consulta",
      "Calculando similaridade de cosseno",
      "Buscando na base de conhecimento",
      "Rodando retrieval nos embeddings",
    ],
    found: [
      "Memória encontrada",
      "Trechos relevantes recuperados",
      "Contexto localizado",
      "Fontes anexadas ao pacote",
    ],
    notFound: [
      "Nenhuma memória relevante",
      "Base sem correspondência",
      "Sem fonte para esta consulta",
    ],
    calling: [
      "Chamando Bobby",
      "Entregando pacote ao Bobby",
      "Acionando motor de resposta",
    ],
    thinking: [
      "Bobby pensando",
      "Bobby estruturando a resposta",
      "Bobby organizando as ideias",
    ],
    typing: ["Bobby digitando"],
  },
};

/** Sorteio sem repetir o último item usado */
const lastPick = new Map<string, number>();
export function pick(key: string, arr: string[]): string {
  if (arr.length === 1) return arr[0];
  let i = Math.floor(Math.random() * arr.length);
  if (lastPick.get(key) === i) i = (i + 1) % arr.length;
  lastPick.set(key, i);
  return arr[i];
}

export function greetingWord(): string {
  const h = new Date().getHours();
  if (h >= 5 && h < 12) return "Bom dia";
  if (h >= 12 && h < 18) return "Boa tarde";
  return "Boa noite";
}

export function dayPart(): "manhã" | "tarde" | "noite" | "madrugada" {
  const h = new Date().getHours();
  if (h >= 5 && h < 12) return "manhã";
  if (h >= 12 && h < 18) return "tarde";
  if (h >= 18 && h < 24) return "noite";
  return "madrugada";
}
